FROM node:18-alpine
WORKDIR /usr/src/app
COPY frontend/package*.json ./
RUN npm ci --silent
COPY frontend/ ./
EXPOSE 3000
CMD ["npm","start"]
FROM node:18-alpine
WORKDIR /usr/src/app
COPY frontend/package*.json ./
RUN npm ci --silent
COPY frontend/ ./
EXPOSE 3000
CMD ["npm","start"]
