name: CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set ANOMALY_CONTAMINATION for tests
        run: echo "ANOMALY_CONTAMINATION=0.05" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install backend deps (light)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.light.txt
      - name: Run backend tests
        run: |
          pytest -q backend/tests || true

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      - name: Build frontend
        run: |
          cd frontend
          npm run build --if-present || true

  backend-ml:
    name: Backend (full ML tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set ANOMALY_CONTAMINATION for tests
        run: echo "ANOMALY_CONTAMINATION=0.05" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install backend full deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run ML backend tests
        run: |
          # ensure SKIP_ML is unset so ML tests run
          pytest -q backend/tests
